import type {
  CatalogItem,
  CustomItem,
  ModuleId,
  Profile,
  ResolvedItem,
  ScenarioId,
} from "./types";
import { KAMS_SHOP } from "./kams";

export const MODULES: {
  id: ModuleId;
  name: string;
  short: string;
  hint: string;
}[] = [
  {
    id: "czerwony",
    name: "Pierwsza pomoc",
    short: "Czerwony",
    hint: "Apteczka, opatrunki, leki, koc termiczny",
  },
  {
    id: "szary",
    name: "Higiena",
    short: "Szary",
    hint: "Mydło, dezynfekcja, papier, worki",
  },
  {
    id: "niebieski",
    name: "Woda i żywność",
    short: "Niebieski",
    hint: "Woda, filtr, racje, kuchenka",
  },
  {
    id: "czarny",
    name: "Schronienie i narzędzia",
    short: "Czarny",
    hint: "Światło, radio, dokumenty, ciepło",
  },
  {
    id: "inne",
    name: "Plecak i organizacja",
    short: "Inne",
    hint: "Sam nośnik, worki, skany",
  },
];

export const CATALOG: CatalogItem[] = [
  {
    id: "apteczka",
    name: "Apteczka podstawowa (rozszerzona urazowo)",
    module: "czerwony",
    weightGrams: 500,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "meds",
    expiryMonths: 12,
    tags: ["fire", "flood", "storm", "work"],
    grabOrder: 4,
    packedLayer: "top",
    notes: "Na wierzchu plecaka, nie na dnie.",
  },
  {
    id: "bandaze",
    name: "Bandaże elastyczne",
    module: "czerwony",
    weightGrams: 30,
    qty: 2,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
    packedLayer: "top",
  },
  {
    id: "gaza",
    name: "Gaza sterylna",
    module: "czerwony",
    weightGrams: 13,
    qty: 3,
    scale: "once",
    minLevel: 1,
    expiry: "meds",
    expiryMonths: 24,
    tags: [],
  },
  {
    id: "plastry",
    name: "Plastry wodoodporne (zestaw)",
    module: "czerwony",
    weightGrams: 30,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "meds",
    expiryMonths: 24,
    tags: [],
    notes: "Plastry wysychają — przegląd co 6 miesięcy.",
  },
  {
    id: "tasma-med",
    name: "Taśma medyczna",
    module: "czerwony",
    weightGrams: 30,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
  },
  {
    id: "nozyczki",
    name: "Nożyczki (tępe końce)",
    module: "czerwony",
    weightGrams: 40,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
    notes: "Bez nich nie utniesz ubrania nad raną.",
  },
  {
    id: "peseta",
    name: "Pęseta",
    module: "czerwony",
    weightGrams: 20,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
  },
  {
    id: "rekawiczki",
    name: "Rękawiczki nitrylowe",
    module: "czerwony",
    weightGrams: 10,
    qty: 3,
    qtyByLevel: { 1: 2, 2: 3, 3: 6 },
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
  },
  {
    id: "koc-nrc",
    name: "Koc termiczny NRC",
    module: "czerwony",
    weightGrams: 60,
    qty: 2,
    scale: "person",
    minLevel: 1,
    expiry: "none",
    tags: ["highway", "heating", "flood"],
    packedLayer: "top",
  },
  {
    id: "leki-podstawowe",
    name: "Paracetamol / ibuprofen",
    module: "czerwony",
    weightGrams: 30,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "meds",
    expiryMonths: 12,
    tags: [],
    grabOrder: 3,
  },
  {
    id: "biegunka",
    name: "Środek przeciwbiegunkowy",
    module: "czerwony",
    weightGrams: 20,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "meds",
    expiryMonths: 12,
    tags: [],
  },
  {
    id: "elektrolity",
    name: "Elektrolity w saszetkach",
    module: "czerwony",
    weightGrams: 5,
    qty: 6,
    scale: "person",
    minLevel: 2,
    expiry: "meds",
    expiryMonths: 24,
    tags: ["highway"],
  },
  {
    id: "leki-osobiste",
    name: "Leki osobiste (3 dni + ulotka)",
    module: "czerwony",
    weightGrams: 50,
    qty: 1,
    scale: "person",
    minLevel: 1,
    expiry: "meds",
    expiryMonths: 6,
    tags: ["flood", "fire"],
    grabOrder: 3,
    notes: "Z ulotką. W stresie nie pamiętasz dawkowania.",
  },
  {
    id: "ffp2",
    name: "Maseczka FFP2",
    module: "czerwony",
    weightGrams: 10,
    qty: 2,
    scale: "eater",
    minLevel: 1,
    expiry: "none",
    tags: ["fire", "industrial", "storm"],
  },
  {
    id: "instrukcja-pp",
    name: "Instrukcja pierwszej pomocy (laminowana)",
    module: "czerwony",
    weightGrams: 30,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
  },
  {
    id: "tourniquet",
    name: "Staza / tourniquet",
    module: "czerwony",
    weightGrams: 80,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: [],
    notes: "Tylko jeśli umiesz używać.",
  },
  {
    id: "epipen",
    name: "EpiPen (anafilaksja)",
    module: "czerwony",
    weightGrams: 80,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "meds",
    expiryMonths: 12,
    tags: ["epipen"],
  },
  {
    id: "insulina",
    name: "Insulina / glukagon + chłodzenie",
    module: "czerwony",
    weightGrams: 120,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "meds",
    expiryMonths: 3,
    tags: ["insulin", "blackout"],
    notes: "Plan B na brak lodówki.",
  },
  {
    id: "syrop-dziecko",
    name: "Apteczka dziecięca (syrop, dawkownik)",
    module: "czerwony",
    weightGrams: 80,
    qty: 1,
    scale: "kid",
    minLevel: 1,
    expiry: "meds",
    expiryMonths: 12,
    tags: [],
    notes: "Dawkowanie wg wagi. Dla dzieci i niemowląt — nie ten sam syrop co u dorosłych.",
  },
  {
    id: "mydlo",
    name: "Mydło (kostka / travel)",
    module: "szary",
    weightGrams: 100,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
  },
  {
    id: "zel",
    name: "Żel antybakteryjny 100 ml (≥60%)",
    module: "szary",
    weightGrams: 110,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: ["work"],
    packedLayer: "pocket",
  },
  {
    id: "chusteczki",
    name: "Chusteczki nawilżane",
    module: "szary",
    weightGrams: 100,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "wipes",
    expiryMonths: 12,
    tags: [],
  },
  {
    id: "recznik",
    name: "Ręcznik z mikrofibry",
    module: "szary",
    weightGrams: 100,
    qty: 1,
    scale: "eater",
    minLevel: 2,
    expiry: "none",
    tags: ["fire"],
  },
  {
    id: "zeby",
    name: "Szczoteczka i pasta",
    module: "szary",
    weightGrams: 50,
    qty: 1,
    scale: "eater",
    minLevel: 2,
    expiry: "none",
    tags: [],
  },
  {
    id: "papier",
    name: "Papier toaletowy (w worku zip-lock)",
    module: "szary",
    weightGrams: 150,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: ["flood"],
    notes: "W hali ewakuacyjnej kończy się w 2 godziny.",
  },
  {
    id: "worki-smieci",
    name: "Worki na śmieci",
    module: "szary",
    weightGrams: 5,
    qty: 10,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: ["storm", "flood"],
    packedLayer: "bottom",
  },
  {
    id: "podpaski",
    name: "Podpaski / tampony",
    module: "szary",
    weightGrams: 5,
    qty: 10,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: [],
    notes: "Też jako opatrunek, filtr, zapłon.",
  },
  {
    id: "tabletki-woda",
    name: "Tabletki do odkażania wody",
    module: "szary",
    weightGrams: 1,
    qty: 30,
    scale: "once",
    minLevel: 1,
    expiry: "tablets",
    expiryMonths: 24,
    tags: ["flood", "blackout", "storm", "coast"],
    packedLayer: "mid",
  },
  {
    id: "kibelek",
    name: "Worki na nieczystości / kibelek",
    module: "szary",
    weightGrams: 40,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["flood"],
  },
  {
    id: "pieluchy",
    name: "Pieluchy (3 dni)",
    module: "szary",
    weightGrams: 400,
    qty: 1,
    scale: "infant",
    minLevel: 1,
    expiry: "none",
    tags: ["infant"],
  },
  {
    id: "woda",
    name: "Woda pitna",
    module: "niebieski",
    weightGrams: 1000,
    qty: 2,
    qtyByLevel: { 1: 1, 2: 2, 3: 2 },
    scale: "person",
    minLevel: 1,
    expiry: "water",
    expiryMonths: 6,
    tags: ["flood", "blackout", "fire", "work", "highway", "storm"],
    grabOrder: 5,
    packedLayer: "bottom",
    notes: "1 L = 1 kg. Resztę uzdatniasz tabletkami / filtrem. Zwierzęta mają wodę przy karmie.",
  },
  {
    id: "butelka-zapas",
    name: "Butelka zapasowa (pusta, szeroki gwint)",
    module: "niebieski",
    weightGrams: 100,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
  },
  {
    id: "filtr",
    name: "Filtr słomkowy",
    module: "niebieski",
    weightGrams: 60,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["flood", "mountains"],
  },
  {
    id: "racje",
    name: "Racje 72h dla dorosłego (liofilizaty + batony + puszki)",
    module: "niebieski",
    weightGrams: 700,
    qty: 1,
    scale: "adult",
    minLevel: 1,
    expiry: "food",
    expiryMonths: 12,
    tags: ["blackout", "highway", "work"],
    packedLayer: "bottom",
    notes: "Min. 2000 kcal/dobę na dorosłego. Dzieci, niemowlęta i zwierzęta mają osobne pozycje.",
  },
  {
    id: "kubek",
    name: "Kubek / menażka metalowa",
    module: "niebieski",
    weightGrams: 150,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: [],
  },
  {
    id: "kuchenka",
    name: "Kuchenka + kartusz",
    module: "niebieski",
    weightGrams: 350,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["blackout", "heating"],
    packedLayer: "bottom",
    notes: "Do gotowania, nigdy do ogrzewania pomieszczenia.",
  },
  {
    id: "sol",
    name: "Sól w saszetkach",
    module: "niebieski",
    weightGrams: 2,
    qty: 5,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: [],
  },
  {
    id: "otwieracz",
    name: "Otwieracz do puszek",
    module: "niebieski",
    weightGrams: 30,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: [],
    notes: "Albo solidny multitool.",
  },
  {
    id: "spork",
    name: "Spork / sztućce",
    module: "niebieski",
    weightGrams: 30,
    qty: 1,
    scale: "eater",
    minLevel: 2,
    expiry: "none",
    tags: [],
  },
  {
    id: "racje-dziecko",
    name: "Racje 72h dla dziecka (musy, batony, dania)",
    module: "niebieski",
    weightGrams: 500,
    qty: 1,
    scale: "child",
    minLevel: 1,
    expiry: "food",
    expiryMonths: 12,
    tags: ["child", "blackout"],
    packedLayer: "bottom",
    notes: "Ok. 1500 kcal/dobę. To, co otworzy bez wrzątku. Nie licz dorosłych liofilizatów.",
  },
  {
    id: "karma-zwierzat",
    name: "Karma i woda dla zwierząt (3 dni)",
    module: "niebieski",
    weightGrams: 600,
    qty: 1,
    scale: "pet",
    minLevel: 1,
    expiry: "food",
    expiryMonths: 6,
    tags: ["pet", "flood"],
    notes: "Nie dziel ludzkich racji z psem. Czekolada i ksylitol są trujące.",
  },
  {
    id: "mleko-proszek",
    name: "Mleko modyfikowane / kaszka",
    module: "niebieski",
    weightGrams: 400,
    qty: 1,
    scale: "infant",
    minLevel: 1,
    expiry: "food",
    expiryMonths: 6,
    tags: ["infant", "blackout"],
    notes: "To, co pije na co dzień. Woda do rozrobienia jest w racjach pitnych, nie w puszkach dla dorosłych.",
  },
  {
    id: "czolowka",
    name: "Latarka czołówka + baterie",
    module: "czarny",
    weightGrams: 80,
    qty: 1,
    scale: "eater",
    minLevel: 1,
    expiry: "batteries",
    expiryMonths: 12,
    tags: ["blackout", "fire", "work", "highway", "storm"],
    packedLayer: "pocket",
  },
  {
    id: "latarka",
    name: "Latarka ręczna zapasowa",
    module: "czarny",
    weightGrams: 80,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "batteries",
    expiryMonths: 12,
    tags: ["blackout", "storm", "fire"],
    packedLayer: "pocket",
  },
  {
    id: "baterie",
    name: "Baterie zapasowe (komplet)",
    module: "czarny",
    weightGrams: 40,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "batteries",
    expiryMonths: 12,
    tags: ["blackout"],
    notes: "Nie mieszaj starych z nowymi.",
  },
  {
    id: "swieca",
    name: "Świeca długopaląca",
    module: "czarny",
    weightGrams: 50,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["blackout", "heating"],
  },
  {
    id: "multitool",
    name: "Multitool / nóż składany",
    module: "czarny",
    weightGrams: 200,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["storm"],
    packedLayer: "pocket",
  },
  {
    id: "duct",
    name: "Taśma naprawcza (duct tape)",
    module: "czarny",
    weightGrams: 100,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["storm"],
  },
  {
    id: "paracord",
    name: "Paracord 10 m",
    module: "czarny",
    weightGrams: 60,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["mountains", "onlyIfRegion"],
  },
  {
    id: "ogien",
    name: "Zapalniczka ×2 + krzesiwo",
    module: "czarny",
    weightGrams: 40,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: [],
    notes: "Dwa niezależne źródła ognia.",
  },
  {
    id: "powerbank",
    name: "Powerbank 10 000 mAh + kabel",
    module: "czarny",
    weightGrams: 250,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: ["blackout", "work", "flood", "highway", "storm", "fire"],
    grabOrder: 2,
    packedLayer: "mid",
    notes: "Sprawdź złącze. Sam powerbank bez kabla nic nie da.",
  },
  {
    id: "radio",
    name: "Radio na baterie / korbkę (FM/AM)",
    module: "czarny",
    weightGrams: 300,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "batteries",
    expiryMonths: 12,
    tags: ["blackout", "storm"],
    packedLayer: "mid",
  },
  {
    id: "gwizdek",
    name: "Gwizdek",
    module: "czarny",
    weightGrams: 10,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: ["fire", "mountains"],
    packedLayer: "pocket",
  },
  {
    id: "poncho",
    name: "Poncho / kurtka przeciwdeszczowa",
    module: "czarny",
    weightGrams: 250,
    qty: 1,
    scale: "eater",
    minLevel: 1,
    expiry: "none",
    tags: ["flood", "storm", "coast"],
    packedLayer: "top",
  },
  {
    id: "warstwa",
    name: "Czapka, rękawiczki, skarpety zapasowe",
    module: "czarny",
    weightGrams: 200,
    qty: 1,
    scale: "eater",
    minLevel: 2,
    expiry: "none",
    tags: ["winter", "highway", "heating"],
  },
  {
    id: "spiwor",
    name: "Śpiwór w worku kompresyjnym",
    module: "czarny",
    weightGrams: 1000,
    qty: 1,
    scale: "eater",
    minLevel: 2,
    expiry: "none",
    tags: ["winter", "highway", "heating", "flood"],
    packedLayer: "bottom",
  },
  {
    id: "karimata",
    name: "Karimata cienka",
    module: "czarny",
    weightGrams: 200,
    qty: 1,
    scale: "eater",
    minLevel: 3,
    expiry: "none",
    tags: ["winter", "heating", "highway"],
    notes: "Bez niej śpiwór traci ciepło do ziemi.",
  },
  {
    id: "dokumenty",
    name: "Dokumenty w worku wodoodpornym",
    module: "czarny",
    weightGrams: 100,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: ["flood", "fire", "work"],
    grabOrder: 1,
    packedLayer: "top",
    notes: "Dowód, polisa, ksero recept, numery ICE.",
  },
  {
    id: "gotowka",
    name: "Gotówka (drobne i średnie nominały)",
    module: "czarny",
    weightGrams: 30,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: ["blackout", "flood", "work"],
    grabOrder: 1,
  },
  {
    id: "mapa",
    name: "Mapa papierowa okolicy",
    module: "czarny",
    weightGrams: 50,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["flood", "highway", "storm", "mountains", "coast"],
    packedLayer: "pocket",
  },
  {
    id: "notes",
    name: "Notes + ołówek",
    module: "czarny",
    weightGrams: 30,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["flood", "work"],
    packedLayer: "pocket",
  },
  {
    id: "okulary",
    name: "Okulary ochronne",
    module: "czarny",
    weightGrams: 40,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["fire", "industrial", "storm"],
  },
  {
    id: "czujnik-czadu",
    name: "Czujnik tlenku węgla (w domu)",
    module: "czarny",
    weightGrams: 150,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "batteries",
    expiryMonths: 12,
    tags: ["heating"],
    notes: "Nie w plecaku — na ścianie. Bezwzględnie przy kuchenkach i świecach.",
  },
  {
    id: "lopatka",
    name: "Łopata składana (auto)",
    module: "czarny",
    weightGrams: 700,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["highway", "onlyIfScenario"],
  },
  {
    id: "buty-biuro",
    name: "Wygodne buty (jeśli w pracy na obcasie)",
    module: "czarny",
    weightGrams: 400,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: ["work", "onlyIfScenario"],
  },
  {
    id: "plecak",
    name: "Plecak 30–45 L z pasem biodrowym",
    module: "inne",
    weightGrams: 1200,
    qty: 1,
    scale: "once",
    minLevel: 1,
    expiry: "none",
    tags: [],
    grabOrder: 6,
    notes: "Czarny, granatowy albo oliwkowy. Bez napisów TACTICAL.",
  },
  {
    id: "worki-kolor",
    name: "Worki kompresyjne (4 kolory modułów)",
    module: "inne",
    weightGrams: 80,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: [],
  },
  {
    id: "pendrive",
    name: "Pendrive ze skanami dokumentów",
    module: "inne",
    weightGrams: 10,
    qty: 1,
    scale: "once",
    minLevel: 2,
    expiry: "none",
    tags: ["flood", "fire"],
  },
  {
    id: "transporter",
    name: "Transporter / klatka dla zwierzęcia",
    module: "inne",
    weightGrams: 1500,
    qty: 1,
    scale: "pet",
    minLevel: 1,
    expiry: "none",
    tags: ["pet", "flood"],
  },
  {
    id: "nosidlo",
    name: "Nosidło / wózek dla małego dziecka",
    module: "inne",
    weightGrams: 800,
    qty: 1,
    scale: "infant",
    minLevel: 1,
    expiry: "none",
    tags: ["infant"],
  },
];

export function peopleCount(p: Profile): number {
  return Math.max(1, p.adults + p.children + p.infants);
}

export function eaterCount(p: Profile): number {
  return Math.max(1, p.adults + p.children);
}

export function kidCount(p: Profile): number {
  return p.children + p.infants;
}

export function carriers(p: Profile): number {
  return Math.max(1, p.adults);
}

function scaleFactor(item: CatalogItem, p: Profile): number {
  switch (item.scale) {
    case "person":
      return peopleCount(p);
    case "eater":
      return eaterCount(p);
    case "kid":
      return kidCount(p);
    case "adult":
      return Math.max(1, p.adults);
    case "child":
      return p.children;
    case "infant":
      return p.infants;
    case "pet":
      return p.pets;
    default:
      return 1;
  }
}

function isVisible(
  item: CatalogItem,
  p: Profile,
  scenario: ScenarioId | null,
): boolean {
  if (item.minLevel > p.level) return false;
  if (item.tags.includes("insulin") && !p.insulin) return false;
  if (item.tags.includes("epipen") && !p.epipen) return false;
  if (item.tags.includes("child") && p.children < 1) return false;
  if (item.tags.includes("infant") && p.infants < 1) return false;
  if (item.tags.includes("pet") && p.pets < 1) return false;
  if (
    (item.id === "spiwor" ||
      item.id === "warstwa" ||
      item.id === "karimata") &&
    !p.winter &&
    !(scenario && item.tags.includes(scenario))
  ) {
    return false;
  }
  if (item.scale === "child" && p.children < 1) return false;
  if (item.scale === "infant" && p.infants < 1) return false;
  if (item.scale === "pet" && p.pets < 1) return false;
  if (item.scale === "kid" && kidCount(p) < 1) return false;
  if (item.tags.includes("onlyIfScenario")) {
    if (!scenario || !item.tags.includes(scenario)) return false;
  }
  if (item.tags.includes("onlyIfRegion")) {
    if (!item.tags.includes(p.region)) return false;
  }
  return true;
}

export function resolveQty(item: CatalogItem, p: Profile): number {
  const base = item.qtyByLevel?.[p.level] ?? item.qty;
  return base * scaleFactor(item, p);
}

export function resolveCatalog(
  p: Profile,
  custom: CustomItem[],
  scenario: ScenarioId | null = null,
): ResolvedItem[] {
  const fromCatalog: ResolvedItem[] = CATALOG.filter((item) =>
    isVisible(item, p, scenario),
  )
    .map((item) => {
      const qty = resolveQty(item, p);
      return {
        id: item.id,
        name: item.name,
        module: item.module,
        qty,
        unitWeight: item.weightGrams,
        weightGrams: item.weightGrams * qty,
        notes: item.notes,
        expiry: item.expiry,
        expiryMonths: item.expiryMonths,
        tags: item.tags,
        grabOrder: item.grabOrder,
        packedLayer: item.packedLayer,
        shopUrl: KAMS_SHOP[item.id]?.url,
        shopLabel: KAMS_SHOP[item.id]?.label,
      };
    })
    .filter((item) => item.qty > 0);

  const fromCustom: ResolvedItem[] = custom.map((item) => ({
    id: item.id,
    name: item.name,
    module: item.module,
    qty: item.qty,
    unitWeight: item.weightGrams,
    weightGrams: item.weightGrams * item.qty,
    expiry: "none" as const,
    tags: ["custom"],
    custom: true,
  }));

  return [...fromCatalog, ...fromCustom];
}

export function weightBudgetGrams(p: Profile): number {
  const humans = peopleCount(p);
  const per = p.level === 1 ? 4500 : p.level === 2 ? 9000 : 8000;
  const petPer = p.level === 1 ? 2000 : 2500;
  return per * humans + petPer * p.pets;
}

export const LEVELS = [
  {
    id: 1 as const,
    name: "Minimum",
    hours: "12–24 h",
    weight: "3–5 kg",
    bag: "20–30 L",
    for: "Miasto, auto, nagła ewakuacja do rodziny.",
  },
  {
    id: 2 as const,
    name: "Standard 72h",
    hours: "72 h",
    weight: "7–10 kg",
    bag: "30–45 L",
    for: "Powódź, blackout, ewakuacja. Sensowny kompromis.",
  },
  {
    id: 3 as const,
    name: "Rodzina",
    hours: "72 h, 2–4 os.",
    weight: "15–25 kg",
    bag: "2 × 40–60 L",
    for: "Dzieci, seniorzy, zwierzęta. Rozłóż na dwa plecaki.",
  },
];

export const REGIONS: { id: Profile["region"]; name: string; hint: string }[] = [
  { id: "city", name: "Miasto", hint: "Blok, komunikacja, tłum" },
  { id: "flood", name: "Dolina / rzeka", hint: "Powódź, woda skażona" },
  { id: "mountains", name: "Lasy / góry", hint: "Mapa, ciepło, gwizdek" },
  { id: "coast", name: "Wybrzeże", hint: "Wiatr, woda słodka" },
  { id: "industrial", name: "Strefa przemysłowa", hint: "FFP3, oczy, dym" },
];
