/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IceRouteImport } from './routes/ice'
import { Route as KopiaRouteImport } from './routes/kopia'
import { Route as PlecakRouteImport } from './routes/plecak'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PrzegladyRouteImport } from './routes/przeglady'
import { Route as TerazRouteImport } from './routes/teraz'
import { Route as WiedzaRouteImport } from './routes/wiedza'
import { Route as WiedzaIndexRouteImport } from './routes/wiedza.index'
import { Route as WiedzaSlugRouteImport } from './routes/wiedza.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IceRoute = IceRouteImport.update({
  id: '/ice',
  path: '/ice',
  getParentRoute: () => rootRouteImport,
} as any)
const KopiaRoute = KopiaRouteImport.update({
  id: '/kopia',
  path: '/kopia',
  getParentRoute: () => rootRouteImport,
} as any)
const PlecakRoute = PlecakRouteImport.update({
  id: '/plecak',
  path: '/plecak',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrzegladyRoute = PrzegladyRouteImport.update({
  id: '/przeglady',
  path: '/przeglady',
  getParentRoute: () => rootRouteImport,
} as any)
const TerazRoute = TerazRouteImport.update({
  id: '/teraz',
  path: '/teraz',
  getParentRoute: () => rootRouteImport,
} as any)
const WiedzaRoute = WiedzaRouteImport.update({
  id: '/wiedza',
  path: '/wiedza',
  getParentRoute: () => rootRouteImport,
} as any)
const WiedzaIndexRoute = WiedzaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WiedzaRoute,
} as any)
const WiedzaSlugRoute = WiedzaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WiedzaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ice': typeof IceRoute
  '/kopia': typeof KopiaRoute
  '/plecak': typeof PlecakRoute
  '/profil': typeof ProfilRoute
  '/przeglady': typeof PrzegladyRoute
  '/teraz': typeof TerazRoute
  '/wiedza': typeof WiedzaRouteWithChildren
  '/wiedza/$slug': typeof WiedzaSlugRoute
  '/wiedza/': typeof WiedzaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ice': typeof IceRoute
  '/kopia': typeof KopiaRoute
  '/plecak': typeof PlecakRoute
  '/profil': typeof ProfilRoute
  '/przeglady': typeof PrzegladyRoute
  '/teraz': typeof TerazRoute
  '/wiedza/$slug': typeof WiedzaSlugRoute
  '/wiedza': typeof WiedzaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ice': typeof IceRoute
  '/kopia': typeof KopiaRoute
  '/plecak': typeof PlecakRoute
  '/profil': typeof ProfilRoute
  '/przeglady': typeof PrzegladyRoute
  '/teraz': typeof TerazRoute
  '/wiedza': typeof WiedzaRouteWithChildren
  '/wiedza/$slug': typeof WiedzaSlugRoute
  '/wiedza/': typeof WiedzaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ice'
    | '/kopia'
    | '/plecak'
    | '/profil'
    | '/przeglady'
    | '/teraz'
    | '/wiedza'
    | '/wiedza/$slug'
    | '/wiedza/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ice'
    | '/kopia'
    | '/plecak'
    | '/profil'
    | '/przeglady'
    | '/teraz'
    | '/wiedza/$slug'
    | '/wiedza'
  id:
    | '__root__'
    | '/'
    | '/ice'
    | '/kopia'
    | '/plecak'
    | '/profil'
    | '/przeglady'
    | '/teraz'
    | '/wiedza'
    | '/wiedza/$slug'
    | '/wiedza/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IceRoute: typeof IceRoute
  KopiaRoute: typeof KopiaRoute
  PlecakRoute: typeof PlecakRoute
  ProfilRoute: typeof ProfilRoute
  PrzegladyRoute: typeof PrzegladyRoute
  TerazRoute: typeof TerazRoute
  WiedzaRoute: typeof WiedzaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ice': {
      id: '/ice'
      path: '/ice'
      fullPath: '/ice'
      preLoaderRoute: typeof IceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopia': {
      id: '/kopia'
      path: '/kopia'
      fullPath: '/kopia'
      preLoaderRoute: typeof KopiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plecak': {
      id: '/plecak'
      path: '/plecak'
      fullPath: '/plecak'
      preLoaderRoute: typeof PlecakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/przeglady': {
      id: '/przeglady'
      path: '/przeglady'
      fullPath: '/przeglady'
      preLoaderRoute: typeof PrzegladyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teraz': {
      id: '/teraz'
      path: '/teraz'
      fullPath: '/teraz'
      preLoaderRoute: typeof TerazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiedza': {
      id: '/wiedza'
      path: '/wiedza'
      fullPath: '/wiedza'
      preLoaderRoute: typeof WiedzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiedza/': {
      id: '/wiedza/'
      path: '/'
      fullPath: '/wiedza/'
      preLoaderRoute: typeof WiedzaIndexRouteImport
      parentRoute: typeof WiedzaRoute
    }
    '/wiedza/$slug': {
      id: '/wiedza/$slug'
      path: '/$slug'
      fullPath: '/wiedza/$slug'
      preLoaderRoute: typeof WiedzaSlugRouteImport
      parentRoute: typeof WiedzaRoute
    }
  }
}

interface WiedzaRouteChildren {
  WiedzaSlugRoute: typeof WiedzaSlugRoute
  WiedzaIndexRoute: typeof WiedzaIndexRoute
}

const WiedzaRouteChildren: WiedzaRouteChildren = {
  WiedzaSlugRoute: WiedzaSlugRoute,
  WiedzaIndexRoute: WiedzaIndexRoute,
}

const WiedzaRouteWithChildren =
  WiedzaRoute._addFileChildren(WiedzaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IceRoute: IceRoute,
  KopiaRoute: KopiaRoute,
  PlecakRoute: PlecakRoute,
  ProfilRoute: ProfilRoute,
  PrzegladyRoute: PrzegladyRoute,
  TerazRoute: TerazRoute,
  WiedzaRoute: WiedzaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
